;
; File generated by cc65 v 2.13.3
;
	.fopt		compiler,"cc65 v 2.13.3"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvblank
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

; no trash
SEI

LDA #0
LDA #10 ; solo necesitamos low bytes!
PHA ;push


PLA ;pull
BEQ L1 ;if A=0
LDA #0 ;if A!=0 -> push 0
PHA
JMP L2
L1: LDA #1 ;if A=0 ->  push 1
    PHA
L2:

;while(1)
papa: JMP papa

.endproc
